[package]
name = "config"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
secrecy = { version = "0.10", features = ["serde"] }
serde = { workspace = true }
figment = { version = "0.10", features = ["toml", "env"] }

[lints]
workspace = true
